package biblioteca.model;

public enum Secao {
    ARTES_E_CULTURA,
    AUTOAJUDA_E_DESENVOLVIMENTO_PESSOAL,
    BIOGRAFIAS_E_AUTOBIOGRAFIAS,
    CIENCIAS_NATURAIS,
    CIENCIAS_SOCIAIS,
    ESPORTES_E_LAZER,
    FICCAO_CIENTIFICA_E_FANTASIA,
    GASTRONOMIA,
    HISTORIA,
    LITERATURA_INFANTIL,
    LITERATURA_JUVENIL,
    MANUSCRITOS,
    POESIA,
    RELIGIAO_E_ESPIRITUALIDADE,
    REVISTAS,
    ROMANCE,
    TECNOLOGIA_E_CIENCIAS_APLICADAS;
}
